import React from 'react';
import Home from './Home.jsx';
import Trip from './Trip.jsx';
import Wedding from './Wedding.jsx';
import {PEOPLE} from './tripPeople.js';
import {useSharedTrip} from './shared.js';

const START=[
{id:'f1',icon:'🛶',name:'Buena Vista rafting',day:'Friday',where:'US-285 / Buena Vista',desc:'A real adventure that works with the drive from Denver to Salida.'},
{id:'f2',icon:'🏎️',name:'High-country ATV / UTV',day:'Friday',where:'Buena Vista',desc:'Guided off-road adventure along the route south.'},
{id:'a1',icon:'🥾',name:'Saturday morning hike',day:'Saturday',where:'Salida area',desc:'Use the open morning before the wedding for a scenic hike close to town, with plenty of time to get back and get ready.'},
{id:'a2',icon:'♨️',name:'Saturday hot springs',day:'Saturday',where:'Salida / Buena Vista area',desc:'A lower-stress adventure before the wedding with time to soak, relax, and be back well before 5 PM.'},
{id:'s1',icon:'🌊',name:"Brown's Canyon rafting",day:'Sunday',where:'Salida / Buena Vista',desc:'Classic Arkansas River adventure close to Salida.'},
{id:'s2',icon:'🪂',name:'Zipline / aerial course',day:'Sunday',where:'Salida / Buena Vista',desc:'High-energy half-day option.'},
{id:'m1',icon:'🌉',name:'Royal Gorge adventure day',day:'Monday',where:'Cañon City',desc:'A bigger excursion for the full open day.'},
{id:'m2',icon:'🏔️',name:'Mountain ATV / UTV day',day:'Monday',where:'Salida region',desc:'A longer off-road day with no schedule pressure.'}
];

function ScriptSummitMark(){return <div className="mark script-summit" aria-label="M Script and Summit logo"><svg viewBox="0 0 64 64" role="img" aria-hidden="true"><path className="script-m" d="M10 39 C17 18,22 17,23 35 C24 46,30 19,37 18 C43 17,37 43,45 38 C49 35,51 29,54 24"/><path className="summit" d="M13 49 L23 41 L30 46 L38 37 L52 49"/><path className="snow" d="M34 41 L38 37 L42 41"/></svg></div>}

export default function App(){
 const[tab,setTab]=React.useState('home');
 const[person,setPerson]=React.useState(localStorage.getItem('trip-person')||'Dan');
 const[selected,setSelected]=React.useState(null);
 const{ideas,setIdeas,votes,setVotes}=useSharedTrip(START);
 React.useEffect(()=>localStorage.setItem('trip-person',person),[person]);
 const add=x=>setIdeas(v=>[...v,{...x,id:'i'+Date.now(),icon:'💡',by:person}]);
 const vote=(id,val)=>setVotes(v=>({...v,[person]:{...(v[person]||{}),[id]:val}}));
 const score=id=>PEOPLE.reduce((n,p)=>n+(votes[p]?.[id]==='yes'?2:votes[p]?.[id]==='maybe'?1:0),0);
 const ranked=[...ideas].sort((a,b)=>score(b.id)-score(a.id));
 return <div className="app-shell"><header className="topbar"><div className="brand"><ScriptSummitMark/><div><h1>Colorado Family Trip</h1><div className="trip-date">September 3–8, 2026 · Salida, Colorado</div></div></div><select className="group-btn" value={person} onChange={e=>setPerson(e.target.value)}>{PEOPLE.map(p=><option key={p}>{p}</option>)}</select></header>
 {tab==='home'&&<Home go={setTab} ranked={ranked} score={score} openIdea={setSelected}/>} {tab==='explore'&&<Explore ideas={ideas} add={add} openIdea={setSelected}/>} {tab==='saturday'&&<Saturday ideas={ideas} openIdea={setSelected}/>} {tab==='vote'&&<Vote ideas={ideas} votes={votes} person={person} vote={vote} score={score} add={add} openIdea={setSelected}/>} {tab==='trip'&&<Trip/>}
 <nav className="bottom-nav five">{[['home','⌂','Home'],['explore','⌕','Explore'],['saturday','💍','Saturday'],['vote','♥','Vote'],['trip','☷','Trip']].map(x=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])}><span>{x[1]}</span><small>{x[2]}</small></button>)}</nav>{selected&&<IdeaModal idea={selected} close={()=>setSelected(null)}/>}</div>
}

function Explore({ideas,add,openIdea}){const[q,setQ]=React.useState(''),[day,setDay]=React.useState('Friday');const shown=ideas.filter(a=>a.day===day&&(!q||(`${a.name} ${a.where} ${a.desc}`).toLowerCase().includes(q.toLowerCase())));return <main className="page"><div className="page-title"><div><div className="overline">EXPLORE</div><h2>Find something to do</h2></div></div><div className="vote-person card"><input style={{border:0,outline:0,width:'65%'}} value={q} onChange={e=>setQ(e.target.value)} placeholder="Search ideas..."/><select value={day} onChange={e=>setDay(e.target.value)}><option>Friday</option><option>Saturday</option><option>Sunday</option><option>Monday</option></select></div><div className="vote-instructions">Friday works with the Denver to Salida drive. Saturday is open until wedding prep. Sunday centers on Salida and Buena Vista. Monday can use a wider radius.</div>{shown.map(a=><button className="activity card activity-button" key={a.id} onClick={()=>openIdea(a)}><div className="activity-head"><div className="activity-icon">{a.icon}</div><div><h3>{a.name}</h3><span className="pill">{a.where}</span></div></div><p>{a.desc}</p></button>)}<QuickAdd add={add}/></main>}
function Saturday({ideas,openIdea}){return <main className="page"><div className="page-title"><div><div className="overline">SATURDAY · SEP 5</div><h2>Adventure + wedding</h2></div></div><div className="vote-instructions"><b>Wedding begins at 5:30 PM.</b><br/>Doors open at 5:00 PM and everyone should be seated by 5:20 PM. The morning and early afternoon are open for something close to Salida.</div>{ideas.filter(a=>a.day==='Saturday').map(a=><button className="activity card activity-button" key={a.id} onClick={()=>openIdea(a)}><div className="activity-head"><div className="activity-icon">{a.icon}</div><div><h3>{a.name}</h3><span className="pill">{a.where}</span></div></div><p>{a.desc}</p></button>)}<div className="section-head"><h3>Wedding schedule</h3></div><div className="card" style={{padding:15}}><Wedding/></div></main>}
function QuickAdd({add}){const[open,setOpen]=React.useState(false),[name,setName]=React.useState(''),[day,setDay]=React.useState('Friday'),[note,setNote]=React.useState('');return <div style={{marginTop:14}}><button className="btn btn-primary" onClick={()=>setOpen(!open)}>＋ Add your own recommendation</button>{open&&<form className="card" style={{padding:14,marginTop:10,display:'grid',gap:8}} onSubmit={e=>{e.preventDefault();if(!name)return;add({name,day,where:'Family suggestion',desc:note});setName('');setNote('');setOpen(false)}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Activity or place"/><select value={day} onChange={e=>setDay(e.target.value)}><option>Friday</option><option>Saturday</option><option>Sunday</option><option>Monday</option></select><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional note"/><button className="gold">Add idea</button></form>}</div>}
function Vote({ideas,votes,person,vote,score,add,openIdea}){return <main className="page"><div className="page-title"><div><div className="overline">FAMILY PICKS</div><h2>What sounds good?</h2></div></div>{ideas.map(a=><div className="activity card" key={a.id}><button className="activity-detail-trigger" onClick={()=>openIdea(a)}><div className="activity-head"><div className="activity-icon">{a.icon}</div><div><h3>{a.name}</h3><span className="pill">{a.day}</span> <span className="cost">{a.where}</span>{a.by&&<p>Added by {a.by}</p>}</div></div><p>{a.desc}</p></button><div className="vote-buttons">{[['yes','❤️ Yes'],['maybe','👍 Maybe'],['no','👎 No']].map(x=><button key={x[0]} className={votes[person]?.[a.id]===x[0]?'chosen':''} onClick={()=>vote(a.id,x[0])}>{x[1]}</button>)}</div><div className="vote-count">Group score: {score(a.id)}</div></div>)}<QuickAdd add={add}/></main>}
function IdeaModal({idea,close}){return <div className="modal-backdrop" onClick={close}><div className="modal-card" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={close}>×</button><div className="activity-icon big-icon">{idea.icon}</div><div className="overline">{idea.day} · {idea.where}</div><h2>{idea.name}</h2><p>{idea.desc}</p><a className="map-link" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(idea.name+' '+idea.where+' Colorado')}`}>Open in Google Maps ↗</a></div></div>}
