import React from 'react';

const PEOPLE=['Dan','Emily','Lyssie','Ashton','Alec','Addison'];
const START=[
{id:'f1',icon:'🛶',name:'Buena Vista rafting',day:'Friday',where:'US-285 / Buena Vista',desc:'Adventure on the drive from Denver to Salida.'},
{id:'f2',icon:'🏎️',name:'High-country ATV / UTV',day:'Friday',where:'Buena Vista',desc:'Guided off-road adventure along the route south.'},
{id:'s1',icon:'🌊',name:"Brown's Canyon rafting",day:'Sunday',where:'Salida / Buena Vista',desc:'Classic Arkansas River adventure close to Salida.'},
{id:'s2',icon:'🪂',name:'Zipline / aerial course',day:'Sunday',where:'Salida / Buena Vista',desc:'High-energy half-day option.'},
{id:'m1',icon:'🌉',name:'Royal Gorge adventure day',day:'Monday',where:'Cañon City',desc:'A bigger excursion for the full open day.'},
{id:'m2',icon:'🏔️',name:'Mountain ATV / UTV day',day:'Monday',where:'Salida region',desc:'A longer off-road day with no schedule pressure.'}
];
const OVER=[['Thu 3','✈️','Arrive Denver'],['Fri 4','🔥','Adventure + Salida'],['Sat 5','💍','Wedding'],['Sun 6','🛶','Adventure day'],['Mon 7','🏎️','Full adventure day'],['Tue 8','✈️','Fly home']];
const PLAN=[
['Thu, Sep 3','Arrive Denver',['4:10 PM · AUS → DEN · DL3669','6:45 PM · Austin group arrives','8:30 PM · ATL → DEN · Frontier','10:05 PM · Alec & Addison arrive','Night · Courtyard by Marriott Denver Airport']],
['Fri, Sep 4','Adventure + drive to Salida',['Morning · Leave Denver','Day · Adventure on or near US-285 / Buena Vista','3:00 PM+ · Airbnb check-in','Evening · Dinner in Salida']],
['Sat, Sep 5','Wedding',['Day · Wedding','Evening · Wedding celebration']],
['Sun, Sep 6','Adventure day',['11:00 AM · Airbnb checkout','Day · Group-selected adventure','Evening · Dinner / flexible plans']],
['Mon, Sep 7','Full adventure day',['Day · Group-selected big adventure','Evening · Final night + pack']],
['Tue, Sep 8','Fly home',['9:30 AM · DEN → AUS · Delta DL3876','10:43 AM · DEN → ATL · Frontier','12:43 PM · Austin group arrives AUS','3:49 PM · Alec & Addison arrive ATL']]
];
const get=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}};

export default function App(){
 const [tab,setTab]=React.useState('home');
 const [person,setPerson]=React.useState(localStorage.getItem('trip-person')||'Dan');
 const [ideas,setIdeas]=React.useState(()=>get('trip-ideas-v3',START));
 const [votes,setVotes]=React.useState(()=>get('trip-votes-v3',{}));
 React.useEffect(()=>localStorage.setItem('trip-person',person),[person]);
 React.useEffect(()=>localStorage.setItem('trip-ideas-v3',JSON.stringify(ideas)),[ideas]);
 React.useEffect(()=>localStorage.setItem('trip-votes-v3',JSON.stringify(votes)),[votes]);
 const add=x=>setIdeas(v=>[...v,{...x,id:'i'+Date.now(),icon:'💡',by:person}]);
 const vote=(id,val)=>setVotes(v=>({...v,[person]:{...(v[person]||{}),[id]:val}}));
 const score=id=>PEOPLE.reduce((n,p)=>n+(votes[p]?.[id]==='yes'?2:votes[p]?.[id]==='maybe'?1:0),0);
 const ranked=[...ideas].sort((a,b)=>score(b.id)-score(a.id));
 return <div className="app-shell"><header className="topbar"><div className="brand"><div className="mark">CO</div><div><div className="overline">SEP 3–8</div><h1>Colorado Family Trip</h1></div></div><select className="group-btn" value={person} onChange={e=>setPerson(e.target.value)}>{PEOPLE.map(p=><option key={p}>{p}</option>)}</select></header>
 {tab==='home'&&<Home go={setTab} ranked={ranked} score={score}/>} {tab==='explore'&&<Explore ideas={ideas} add={add}/>} {tab==='vote'&&<Vote ideas={ideas} votes={votes} person={person} vote={vote} score={score} add={add}/>} {tab==='trip'&&<Trip/>}
 <nav className="bottom-nav">{[['home','⌂','Home'],['explore','⌕','Explore'],['vote','♥','Vote'],['trip','☷','Trip']].map(x=><button key={x[0]} className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])}><span>{x[1]}</span><small>{x[2]}</small></button>)}</nav></div>
}
function Home({go,ranked,score}){return <main className="page"><section className="hero card"><div className="overline light">SALIDA, COLORADO</div><h2>Wedding trip.<br/>Packed with adventure.</h2><p>Vote, add ideas, and fill the three open days together.</p><div className="hero-actions"><button className="gold" onClick={()=>go('explore')}>Explore ideas →</button><button className="ghost" onClick={()=>go('vote')}>Vote</button></div></section><div className="section-head"><h3>Trip overview</h3><button onClick={()=>go('trip')}>Details →</button></div><div className="card" style={{padding:12}}>{OVER.map((x,i)=><div key={x[0]} style={{display:'grid',gridTemplateColumns:'58px 28px 1fr 44px',alignItems:'center',padding:'10px 4px',borderBottom:i<5?'1px solid #eeeae0':'none'}}><b style={{fontSize:11}}>{x[0]}</b><span>{x[1]}</span><strong style={{fontSize:13}}>{x[2]}</strong>{[1,3,4].includes(i)&&<span className="pill">OPEN</span>}</div>)}</div><div className="section-head"><h3>Group favorites</h3><button onClick={()=>go('vote')}>Vote →</button></div>{ranked.slice(0,3).map((a,i)=><div className="rank card" key={a.id}><div className="rank-num">{i+1}</div><div><b>{a.name}</b><p>{a.day} · {a.where}</p></div><b>{score(a.id)} pts</b></div>)}</main>}
function Explore({ideas,add}){const [q,setQ]=React.useState(''),[day,setDay]=React.useState('Friday');const shown=ideas.filter(a=>a.day===day&&(!q||(`${a.name} ${a.where} ${a.desc}`).toLowerCase().includes(q.toLowerCase())));return <main className="page"><div className="page-title"><div><div className="overline">EXPLORE</div><h2>Find something to do</h2></div></div><div className="vote-person card"><input style={{border:0,outline:0,width:'65%'}} value={q} onChange={e=>setQ(e.target.value)} placeholder="Search ideas..."/><select value={day} onChange={e=>setDay(e.target.value)}><option>Friday</option><option>Sunday</option><option>Monday</option></select></div><div className="vote-instructions">{day==='Friday'?'Friday is an adventure day. Ideas are optimized for the Denver → Salida route, especially the US-285 / Buena Vista corridor.':day==='Sunday'?'Sunday centers on Salida and Buena Vista.':'Monday can use a wider radius because the full day is open.'}</div>{shown.map(a=><div className="activity card" key={a.id}><div className="activity-head"><div className="activity-icon">{a.icon}</div><div><h3>{a.name}</h3><span className="pill">{a.where}</span></div></div><p>{a.desc}</p></div>)}<QuickAdd add={add}/></main>}
function QuickAdd({add}){const [open,setOpen]=React.useState(false),[name,setName]=React.useState(''),[day,setDay]=React.useState('Friday'),[note,setNote]=React.useState('');return <div style={{marginTop:14}}><button className="btn btn-primary" onClick={()=>setOpen(!open)}>＋ Add your own recommendation</button>{open&&<form className="card" style={{padding:14,marginTop:10,display:'grid',gap:8}} onSubmit={e=>{e.preventDefault();if(!name)return;add({name,day,where:'Family suggestion',desc:note});setName('');setNote('');setOpen(false)}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Activity or place"/><select value={day} onChange={e=>setDay(e.target.value)}><option>Friday</option><option>Sunday</option><option>Monday</option></select><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional note"/><button className="gold">Add idea</button></form>}</div>}
function Vote({ideas,votes,person,vote,score,add}){return <main className="page"><div className="page-title"><div><div className="overline">FAMILY PICKS</div><h2>What sounds good?</h2></div></div>{ideas.map(a=><div className="activity card" key={a.id}><div className="activity-head"><div className="activity-icon">{a.icon}</div><div><h3>{a.name}</h3><span className="pill">{a.day}</span> <span className="cost">{a.where}</span>{a.by&&<p>Added by {a.by}</p>}</div></div><div className="vote-buttons">{[['yes','❤️ Yes'],['maybe','👍 Maybe'],['no','👎 No']].map(x=><button key={x[0]} className={votes[person]?.[a.id]===x[0]?'chosen':''} onClick={()=>vote(a.id,x[0])}>{x[1]}</button>)}</div><div className="vote-count">Group score: {score(a.id)}</div></div>)}<QuickAdd add={add}/></main>}
function Trip(){return <main className="page"><div className="page-title"><div><div className="overline">DETAILS</div><h2>Trip itinerary</h2></div></div>{PLAN.map(d=><section className="day" key={d[0]}><div className="day-title"><div><small>{d[0]}</small><h3>{d[1]}</h3></div></div><div className="timeline">{d[2].map((x,i)=><div className="timeline-row" key={i}><div><b>{x}</b></div></div>)}</div></section>)}<div className="section-head"><h3>Stays</h3></div><div className="stay card"><div className="stay-icon">🏨</div><div><h3>Courtyard by Marriott Denver Airport at Gateway Park</h3><small>Thu Sep 3 → Fri Sep 4 · 4343 Airport Way</small></div></div><div className="stay card"><div className="stay-icon">🏡</div><div><h3>Home in Salida</h3><small>Fri Sep 4, 3:00 PM → Sun Sep 6, 11:00 AM · 306 Shepherd Road</small></div></div></main>}
