import React from 'react';
import Wedding from './Wedding.jsx';
import StayDetails from './StayDetails.jsx';
const days=[
{d:'Thu, Sep 3',t:'Arrive Denver',s:'Flights + airport hotel',i:['4:10 PM · AUS → DEN · Delta DL3669','6:45 PM · Austin group arrives DEN','8:30 PM · ATL → DEN · Frontier','10:05 PM · Alec & Addison arrive DEN','Night · Courtyard by Marriott Denver Airport']},
{d:'Fri, Sep 4',t:'Adventure + Salida',s:'Make the drive part of the adventure',i:['Morning · Leave Denver','Day · Adventure on or near US-285 / Buena Vista','3:00 PM+ · Airbnb check-in','Evening · Dinner in Salida']},
{d:'Sat, Sep 5',t:'Adventure + Wedding',s:'Morning and early afternoon open · wedding at 5:30 PM',w:true},
{d:'Sun, Sep 6',t:'Adventure day',s:'Salida / Buena Vista',i:['11:00 AM · Airbnb checkout','Day · Group-selected adventure','Evening · Dinner / flexible plans']},
{d:'Mon, Sep 7',t:'Full adventure day',s:'Go big',i:['Day · Group-selected big adventure','Evening · Final night + pack']},
{d:'Tue, Sep 8',t:'Fly home',s:'Denver departures',i:['9:30 AM · DEN → AUS · Delta DL3876','10:43 AM · DEN → ATL · Frontier','12:43 PM · Austin group arrives AUS','3:49 PM · Alec & Addison arrive ATL']}
];
export default function Trip(){const[open,setOpen]=React.useState('Sat, Sep 5'),[stay,setStay]=React.useState(null);return <main className="page"><div className="page-title"><div><div className="overline">DETAILS</div><h2>Trip itinerary</h2></div></div>{days.map(x=><section className="card" style={{marginBottom:10,overflow:'hidden'}} key={x.d}><button onClick={()=>setOpen(open===x.d?'':x.d)} style={{width:'100%',border:0,background:'white',padding:15,textAlign:'left',display:'grid',gridTemplateColumns:'1fr 22px'}}><div><small style={{color:'#747b75',fontWeight:800}}>{x.d}</small><h3 style={{margin:'3px 0',fontSize:16}}>{x.t}</h3><span style={{fontSize:10,color:'#747b75'}}>{x.s}</span></div><b>{open===x.d?'−':'+'}</b></button>{open===x.d&&<div style={{padding:'0 15px 15px'}}>{x.w?<><div className="vote-instructions"><b>Open before the wedding:</b> morning through early afternoon. Doors open at 5:00 PM and everyone should be seated by 5:20 PM.</div><Wedding/></>:x.i.map((v,i)=><div key={i} style={{padding:'9px 0',borderTop:'1px solid #eeeae0',fontSize:12}}>{v}</div>)}</div>}</section>)}<div className="section-head"><h3>Stays</h3></div><button className="stay card stay-button" onClick={()=>setStay('hotel')}><div className="stay-icon">🏨</div><div><h3>Courtyard by Marriott Denver Airport at Gateway Park</h3><small>Thu Sep 3 → Fri Sep 4 · 4343 Airport Way, Denver</small><p>Tap for full details and map.</p></div></button><button className="stay card stay-button" onClick={()=>setStay('airbnb')}><div className="stay-icon">🏡</div><div><h3>Home in Salida</h3><small>306 Shepherd Road, Unit A · Salida, CO 81201</small><p>Fri Sep 4 · 3:00 PM → Sun Sep 6 · 11:00 AM</p><p>Tap for full details and map.</p></div></button>{stay&&<StayDetails type={stay} close={()=>setStay(null)}/>}</main>}
